import Foundation
import SwiftUI

// MARK: - Supported Languages

enum AppLanguage: String, CaseIterable, Identifiable {
    case english  = "en"
    case spanish  = "es"
    case korean   = "ko"
    case chinese  = "zh-Hans"
    case vietnamese = "vi"
    case french   = "fr"
    case farsi    = "fa"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english:    return "English"
        case .spanish:    return "Español"
        case .korean:     return "한국어"
        case .chinese:    return "中文"
        case .vietnamese: return "Tiếng Việt"
        case .french:     return "Français"
        case .farsi:      return "فارسی"
        }
    }

    var flag: String {
        switch self {
        case .english:    return "🇺🇸"
        case .spanish:    return "🇪🇸"
        case .korean:     return "🇰🇷"
        case .chinese:    return "🇨🇳"
        case .vietnamese: return "🇻🇳"
        case .french:     return "🇫🇷"
        case .farsi:      return "🇮🇷"
        }
    }

    /// BCP 47 language tag for the AI chat system prompt
    var bcp47: String { rawValue }
}

// MARK: - Localization Manager

/// Provides translated strings for the current app language.
/// Falls back to English for any missing keys.
@MainActor
final class L10n {
    static var current: AppLanguage {
        let code = UserDefaults.standard.string(forKey: "appLanguage") ?? "en"
        return AppLanguage(rawValue: code) ?? .english
    }

    /// Main lookup — returns the translated string for the current language.
    static func t(_ key: String) -> String {
        let lang = current
        guard let table = translations[lang.rawValue],
              let value = table[key] else {
            // Fallback to English
            return translations["en"]?[key] ?? key
        }
        return value
    }

    // MARK: - Translation Tables

    static let translations: [String: [String: String]] = [
        "en": en,
        "es": es,
        "ko": ko,
        "zh-Hans": zhHans,
        "vi": vi,
        "fr": fr,
        "fa": fa,
    ]

    // MARK: - English (Base)

    static let en: [String: String] = [
        // Tabs
        "tab.watches": "Watches",
        "tab.savings": "Savings",
        "savings.potential_label": "Potential Savings",
        "savings.community_header": "Stewards are saving big!",
        "tab.activity": "Activity",
        "tab.settings": "Settings",

        // Home Screen
        "home.title": "Watches",
        "home.subtitle": "Steward keeps watch so you don't have to",
        "home.app_title": "Steward",
        "home.app_subtitle": "Your personal AI concierge",
        "home.notifications": "Notifications",
        "home.chat_prompt": "Ask Steward to watch something…",
        "home.steward_working": "Steward is working for you",
        "home.checks": "Checks",
        "home.time_saved": "Time\nsaved",
        "home.triggers": "Triggers",
        "home.potential_savings": "Potential\nsavings",
        "home.view_all_savings": "View all potential savings",
        "home.price_insights": "Price Insights",
        "home.price_insights.tracking": "Tracking %d prices · Tap to see deals",
        "home.price_insights.locked": "Upgrade to Pro to see deals & price trends",
        "home.price_insights.pro": "PRO",
        "home.active_watches": "Active Watches",
        "home.edit": "Edit",
        "home.done": "Done",
        "home.empty.title": "No watches yet",
        "home.empty.subtitle": "Tell Steward what to monitor and it'll\nwatch the web for you around the clock.",
        "home.add_watch": "Add a new watch via Steward AI",
        "home.delete_watch": "Delete Watch",
        "home.select_all": "Select All",
        "home.deselect_all": "Deselect All",
        "home.delete_count": "Delete (%d)",
        "home.delete_confirm": "Delete %d watches?",
        "home.delete_warning": "This action cannot be undone.",
        "home.triggered.cart": "READY TO ADD TO CART",
        "home.triggered.book": "READY TO BOOK",
        "home.triggered.price": "PRICE TARGET HIT",
        "home.triggered.form": "READY TO SUBMIT",
        "home.triggered.notify": "CHANGE DETECTED",
        "home.review": "Review →",
        "home.savings.title": "Potential Savings",
        "home.filter.all": "All",
        "home.filter.active": "Active",
        "home.filter.triggered": "Triggered",
        "home.filter.paused": "Paused",

        // Activity Screen
        "activity.title": "Activity",
        "activity.subtitle": "Everything Steward has handled for you",
        "activity.empty.title": "No activity yet",
        "activity.empty.subtitle": "When Steward acts on your behalf,\nyou'll see a timeline of everything here.",
        "activity.empty.filtered": "Activities matching this filter\nwill appear here.",
        "activity.filter.all": "All",
        "activity.filter.lifecycle": "Lifecycle",
        "activity.filter.actions": "Actions",
        "activity.filter.alerts": "Alerts",
        "activity.steward_at_work": "Steward at Work",
        "activity.past_7_days": "Past 7 days",
        "activity.loading_stats": "Loading stats…",
        "activity.no_watches": "Create a watch and Steward will start working for you.",
        "activity.monitoring": "Steward is monitoring %d %@. Checks will appear here soon.",
        "activity.weekly_checks": "Steward checked your watches **%@ %@** this week so you didn't have to.",
        "activity.check": "check",
        "activity.checks": "checks",
        "activity.trigger": "trigger",
        "activity.triggers": "triggers",
        "activity.action": "action",
        "activity.actions": "actions",
        "activity.watch": "watch",
        "activity.watches": "watches",
        "activity.time": "time",
        "activity.times": "times",

        // Settings Screen
        "settings.title": "Settings",
        "settings.subtitle": "Personalise how Steward serves you",
        "settings.appearance": "Appearance",
        "settings.dark_mode": "Dark mode",
        "settings.notifications": "Notifications",
        "settings.push": "Push notifications",
        "settings.quiet_hours": "Quiet hours",
        "settings.quiet_hours.desc": "Silence notifications during set hours",
        "settings.from": "From",
        "settings.to": "to",
        "settings.watch_defaults": "Watch Defaults",
        "settings.default_frequency": "Default frequency",
        "settings.when_triggered": "When triggered",
        "settings.when_triggered.desc": "Default for new watches",
        "settings.currency": "Currency",
        "settings.language": "Language",
        "settings.account": "Account",
        "settings.plan": "Plan",
        "settings.restore": "Restore purchases",
        "settings.replay_tour": "Replay welcome tour",
        "settings.privacy": "Privacy Policy",
        "settings.terms": "Terms of Service",
        "settings.sign_out": "Sign Out",
        "settings.apple_id": "Apple ID account",

        // Detail Screen
        "detail.back": "Back",
        "detail.rename": "Rename",
        "detail.rename_title": "Rename Watch",
        "detail.rename_placeholder": "Watch name",
        "detail.rename_message": "Enter a new name for this watch.",
        "detail.delete_confirm": "Are you sure you want to delete \"%@\"? This action cannot be undone.",
        "detail.status.triggered": "Change detected · Ready to act",
        "detail.status.attention": "Needs attention · %d failures",
        "detail.status.watching": "Watching · %@",
        "detail.price_history": "Price History",
        "detail.loading_prices": "Loading price data...",
        "detail.waiting_prices": "Waiting for price data",
        "detail.waiting_prices.desc": "Steward will start tracking prices on the next watch. Price history will appear here as data is collected.",
        "detail.change_detected": "DETECTED CHANGE",
        "detail.needs_attention": "NEEDS ATTENTION",
        "detail.trouble_checking": "This watch is having trouble checking the page.",
        "detail.failed_count": "Failed %d times in a row. The page may have changed or the URL may no longer work.",
        "detail.ask_ai_fix": "Ask AI to fix",
        "detail.find_link": "Find link",
        "detail.action_link": "Action link",
        "detail.watching_for": "Watching for",
        "detail.ai_will": "AI will",
        "detail.watch_frequency": "Watch frequency",
        "detail.watch_start_time": "Watch start time",
        "detail.next_watch": "Next watch",
        "detail.notify_via": "Notify via",
        "detail.not_set": "Not set",
        "detail.condition_met_action": "Your condition was met · Tap to %@",
        "detail.condition_met": "Your condition was met · Steward can act now",
        "detail.let_steward_act": "Let Steward act now",
        "detail.no_results": "No results yet. Steward will start monitoring soon",
        "detail.when_triggered": "When Triggered",
        "detail.notify_me": "Notify Me",
        "detail.notify_quick_link": "Notify + Quick Link",
        "detail.steward_acts": "Steward Acts",
        "detail.beta": "Beta",
        "detail.premium": "Premium",
        "detail.only_act_under": "Only act if under",
        "detail.no_limit": "No limit",
        "detail.waiting": "⏳ Waiting for trigger…",
        "detail.delete_watch": "Delete Watch",
        "detail.visit_website": "Visit Website",
        "detail.copy_url": "Copy URL",
        "detail.share_watch": "Share this watch",
        "detail.share_watch.desc": "Invite a friend to watch this too",
        "detail.watch_history": "Watch History",
        "detail.no_change": "No change detected",

        // Chat
        "chat.initial": "Hello! 👋 I'm Steward, your personal web watcher. I keep an eye on websites and take action on your behalf. What can I help you with?",
        "chat.suggestion.price": "Track a price drop",
        "chat.suggestion.restock": "Watch for a restock",
        "chat.suggestion.tickets": "Find tickets or appointments",
        "chat.suggestion.booking": "Monitor a booking",
        "chat.placeholder": "Describe what to watch…",

        // Savings
        "savings.title": "Potential Savings",
        "savings.subtitle": "Prices Steward caught dropping for you",
        "savings.price_changes": "Price Changes",
        "savings.sort.newest": "Newest",
        "savings.sort.oldest": "Oldest",
        "savings.sort.biggest": "Biggest Savings",
        "savings.sort.name": "Watch Name",
        "savings.empty.title": "No price changes yet",
        "savings.empty.subtitle": "When Steward detects price changes\non your watches, they'll appear here.",

        // Watch Card
        "watch.tracking_stores": "Tracking across stores",
        "watch.change_detected": "Change detected!",
        "watch.needs_attention": "Needs attention",

        // Action Modal
        "action.title.price": "Price target hit!",
        "action.title.cart": "Item is available!",
        "action.title.book": "Slot found!",
        "action.title.form": "Ready to submit!",
        "action.title.notify": "Change detected!",
        "action.done.price": "Deal page opened!",
        "action.done.cart": "Product page opened!",
        "action.done.book": "Booking page opened!",
        "action.done.form": "Form page opened!",
        "action.done.notify": "Change acknowledged!",
        "action.tap_to_act": "Tap below to open the page and complete your action",
        "action.condition_met": "Your watched condition has been met",
        "action.page": "Page",
        "action.change": "Change detected",
        "action.action": "Action",
        "action.copied": "Copied!",
        "action.promo_detected": "Promo code detected",
        "action.not_now": "Not now",
        "action.got_it": "Got it",
        "action.working": "Steward is working…",
        "action.completing": "Completing action on your behalf",
        "action.back_home": "Back to home",
        "action.steward_suggests": "Steward suggests",
        "action.suggest.restock": "Watch for future restocks",
        "action.suggest.price_drops": "Track price drops",
        "action.suggest.deeper": "Keep watching for a bigger drop",
        "action.suggest.restock_cart": "Watch for restocks too",
        "action.suggest.earlier_slot": "Watch for an earlier slot",
        "action.suggest.keep_watching": "Keep watching for changes",

        // Onboarding
        "onboarding.skip": "Skip",
        "onboarding.next": "Next",
        "onboarding.get_started": "Get Started",

        // Common
        "common.cancel": "Cancel",
        "common.done": "Done",
        "common.delete": "Delete",
        "common.save": "Save",
        "common.back": "Back",
        "common.confirm": "Confirm",
        "common.upgrade": "Upgrade",
        "common.loading": "Loading…",

        // Tier gating
        "tier.locked_reason.quickLink": "Notify + Quick Link is a Pro feature",
        "tier.locked_reason.stewardActs": "Steward Acts is a Premium feature",
    ]

    // MARK: - Spanish

    static let es: [String: String] = [
        // Tabs
        "tab.watches": "Vigilancias",
        "tab.savings": "Ahorros",
        "savings.potential_label": "Ahorro Potencial",
        "savings.community_header": "¡Los Stewards están ahorrando mucho!",
        "tab.activity": "Actividad",
        "tab.settings": "Ajustes",

        // Home Screen
        "home.title": "Vigilancias",
        "home.subtitle": "Steward vigila para que tú no tengas que hacerlo",
        "home.app_title": "Steward",
        "home.app_subtitle": "Tu asistente personal con IA",
        "home.steward_working": "Steward está trabajando para ti",
        "home.checks": "Revisiones",
        "home.time_saved": "Tiempo\nahorrado",
        "home.triggers": "Alertas",
        "home.potential_savings": "Ahorro\npotencial",
        "home.notifications": "Notificaciones",
        "home.chat_prompt": "Pide a Steward que vigile algo…",
        "home.view_all_savings": "Ver todos los ahorros",
        "home.price_insights": "Análisis de Precios",
        "home.price_insights.tracking": "Rastreando %d precios · Toca para ver ofertas",
        "home.price_insights.locked": "Mejora a Pro para ver ofertas y tendencias de precios",
        "home.price_insights.pro": "PRO",
        "home.active_watches": "Vigilancias Activas",
        "home.edit": "Editar",
        "home.done": "Listo",
        "home.empty.title": "Sin vigilancias aún",
        "home.empty.subtitle": "Dile a Steward qué monitorear y vigilará\nla web por ti las 24 horas.",
        "home.add_watch": "Añadir vigilancia con Steward AI",
        "home.delete_watch": "Eliminar Vigilancia",
        "home.select_all": "Seleccionar todo",
        "home.deselect_all": "Deseleccionar todo",
        "home.delete_count": "Eliminar (%d)",
        "home.delete_confirm": "¿Eliminar %d vigilancias?",
        "home.delete_warning": "Esta acción no se puede deshacer.",
        "home.triggered.cart": "LISTO PARA AÑADIR AL CARRITO",
        "home.triggered.book": "LISTO PARA RESERVAR",
        "home.triggered.price": "PRECIO OBJETIVO ALCANZADO",
        "home.triggered.form": "LISTO PARA ENVIAR",
        "home.triggered.notify": "CAMBIO DETECTADO",
        "home.review": "Revisar →",
        "home.savings.title": "Ahorro Potencial",
        "home.filter.all": "Todo",
        "home.filter.active": "Activo",
        "home.filter.triggered": "Activado",
        "home.filter.paused": "Pausado",

        // Activity Screen
        "activity.title": "Actividad",
        "activity.subtitle": "Todo lo que Steward ha hecho por ti",
        "activity.empty.title": "Sin actividad aún",
        "activity.empty.subtitle": "Cuando Steward actúe por ti,\nverás un historial de todo aquí.",
        "activity.empty.filtered": "Las actividades de este filtro\naparecerán aquí.",
        "activity.filter.all": "Todo",
        "activity.filter.lifecycle": "Ciclo de vida",
        "activity.filter.actions": "Acciones",
        "activity.filter.alerts": "Alertas",
        "activity.steward_at_work": "Steward Trabajando",
        "activity.past_7_days": "Últimos 7 días",
        "activity.loading_stats": "Cargando estadísticas…",
        "activity.no_watches": "Crea una vigilancia y Steward empezará a trabajar por ti.",
        "activity.monitoring": "Steward está monitoreando %d %@. Las verificaciones aparecerán pronto.",
        "activity.weekly_checks": "Steward revisó tus vigilancias **%@ %@** esta semana para que no tuvieras que hacerlo.",
        "activity.check": "verificación",
        "activity.checks": "verificaciones",
        "activity.trigger": "activación",
        "activity.triggers": "activaciones",
        "activity.action": "acción",
        "activity.actions": "acciones",
        "activity.watch": "vigilancia",
        "activity.watches": "vigilancias",
        "activity.time": "vez",
        "activity.times": "veces",

        // Settings Screen
        "settings.title": "Ajustes",
        "settings.subtitle": "Personaliza cómo Steward te sirve",
        "settings.appearance": "Apariencia",
        "settings.dark_mode": "Modo oscuro",
        "settings.notifications": "Notificaciones",
        "settings.push": "Notificaciones push",
        "settings.quiet_hours": "Horas silenciosas",
        "settings.quiet_hours.desc": "Silenciar notificaciones durante horas establecidas",
        "settings.from": "De",
        "settings.to": "a",
        "settings.watch_defaults": "Valores Predeterminados",
        "settings.default_frequency": "Frecuencia predeterminada",
        "settings.when_triggered": "Al activarse",
        "settings.when_triggered.desc": "Predeterminado para nuevas vigilancias",
        "settings.currency": "Moneda",
        "settings.language": "Idioma",
        "settings.account": "Cuenta",
        "settings.plan": "Plan",
        "settings.restore": "Restaurar compras",
        "settings.replay_tour": "Repetir tour de bienvenida",
        "settings.privacy": "Política de Privacidad",
        "settings.terms": "Términos de Servicio",
        "settings.sign_out": "Cerrar Sesión",
        "settings.apple_id": "Cuenta de Apple ID",

        // Detail Screen
        "detail.back": "Atrás",
        "detail.rename": "Renombrar",
        "detail.rename_title": "Renombrar Vigilancia",
        "detail.rename_placeholder": "Nombre de la vigilancia",
        "detail.rename_message": "Introduce un nuevo nombre para esta vigilancia.",
        "detail.delete_confirm": "¿Seguro que quieres eliminar \"%@\"? Esta acción no se puede deshacer.",
        "detail.status.triggered": "Cambio detectado · Listo para actuar",
        "detail.status.attention": "Requiere atención · %d fallos",
        "detail.status.watching": "Vigilando · %@",
        "detail.price_history": "Historial de Precios",
        "detail.loading_prices": "Cargando datos de precios...",
        "detail.waiting_prices": "Esperando datos de precios",
        "detail.waiting_prices.desc": "Steward comenzará a rastrear precios en la próxima vigilancia. El historial de precios aparecerá aquí a medida que se recopilen datos.",
        "detail.change_detected": "CAMBIO DETECTADO",
        "detail.needs_attention": "REQUIERE ATENCIÓN",
        "detail.trouble_checking": "Esta vigilancia tiene problemas para verificar la página.",
        "detail.failed_count": "Falló %d veces seguidas. La página puede haber cambiado o la URL puede que ya no funcione.",
        "detail.ask_ai_fix": "Pedir a la IA que lo arregle",
        "detail.find_link": "Buscar enlace",
        "detail.action_link": "Enlace de acción",
        "detail.watching_for": "Vigilando",
        "detail.ai_will": "La IA hará",
        "detail.watch_frequency": "Frecuencia de vigilancia",
        "detail.watch_start_time": "Hora de inicio",
        "detail.next_watch": "Próxima vigilancia",
        "detail.notify_via": "Notificar por",
        "detail.not_set": "No configurado",
        "detail.condition_met_action": "Tu condición se cumplió · Toca para %@",
        "detail.condition_met": "Tu condición se cumplió · Steward puede actuar ahora",
        "detail.let_steward_act": "Dejar que Steward actúe ahora",
        "detail.no_results": "Sin resultados aún. Steward comenzará a monitorear pronto",
        "detail.when_triggered": "Al Activarse",
        "detail.notify_me": "Solo Notificar",
        "detail.notify_quick_link": "Notificar + Enlace",
        "detail.steward_acts": "Steward Actúa",
        "detail.beta": "Beta",
        "detail.premium": "Premium",
        "detail.only_act_under": "Solo actuar si es menor a",
        "detail.no_limit": "Sin límite",
        "detail.waiting": "⏳ Esperando activación…",
        "detail.delete_watch": "Eliminar Vigilancia",
        "detail.visit_website": "Visitar Sitio Web",
        "detail.copy_url": "Copiar URL",
        "detail.share_watch": "Compartir vigilancia",
        "detail.share_watch.desc": "Invita a un amigo a vigilar esto también",
        "detail.watch_history": "Historial",
        "detail.no_change": "Sin cambios detectados",

        // Chat
        "chat.initial": "¡Hola! 👋 Soy Steward, tu vigilante personal de sitios web. Monitoreo páginas y actúo en tu nombre. ¿En qué puedo ayudarte?",
        "chat.suggestion.price": "Rastrear una baja de precio",
        "chat.suggestion.restock": "Vigilar un reabastecimiento",
        "chat.suggestion.tickets": "Buscar boletos o citas",
        "chat.suggestion.booking": "Monitorear una reserva",
        "chat.placeholder": "Describe qué vigilar…",

        // Savings
        "savings.title": "Ahorro Potencial",
        "savings.subtitle": "Precios que Steward detectó en baja para ti",
        "savings.price_changes": "Cambios de Precio",
        "savings.sort.newest": "Más recientes",
        "savings.sort.oldest": "Más antiguos",
        "savings.sort.biggest": "Mayor ahorro",
        "savings.sort.name": "Nombre de vigilancia",
        "savings.empty.title": "Sin cambios de precio aún",
        "savings.empty.subtitle": "Cuando Steward detecte cambios de precio\nen tus vigilancias, aparecerán aquí.",

        // Watch Card
        "watch.tracking_stores": "Rastreando en tiendas",
        "watch.change_detected": "¡Cambio detectado!",
        "watch.needs_attention": "Requiere atención",

        // Action Modal
        "action.title.price": "¡Precio objetivo alcanzado!",
        "action.title.cart": "¡Artículo disponible!",
        "action.title.book": "¡Plaza encontrada!",
        "action.title.form": "¡Listo para enviar!",
        "action.title.notify": "¡Cambio detectado!",
        "action.done.price": "¡Página de oferta abierta!",
        "action.done.cart": "¡Página del producto abierta!",
        "action.done.book": "¡Página de reserva abierta!",
        "action.done.form": "¡Página del formulario abierta!",
        "action.done.notify": "¡Cambio confirmado!",
        "action.tap_to_act": "Toca abajo para abrir la página y completar tu acción",
        "action.condition_met": "Tu condición vigilada se ha cumplido",
        "action.page": "Página",
        "action.change": "Cambio detectado",
        "action.action": "Acción",
        "action.copied": "¡Copiado!",
        "action.promo_detected": "Código promocional detectado",
        "action.not_now": "Ahora no",
        "action.got_it": "Entendido",
        "action.working": "Steward está trabajando…",
        "action.completing": "Completando la acción en tu nombre",
        "action.back_home": "Volver al inicio",
        "action.steward_suggests": "Steward sugiere",
        "action.suggest.restock": "Vigilar futuros reabastecimientos",
        "action.suggest.price_drops": "Rastrear bajadas de precio",
        "action.suggest.deeper": "Seguir vigilando una bajada mayor",
        "action.suggest.restock_cart": "Vigilar reabastecimientos también",
        "action.suggest.earlier_slot": "Vigilar una plaza más temprana",
        "action.suggest.keep_watching": "Seguir vigilando cambios",

        // Onboarding
        "onboarding.skip": "Omitir",
        "onboarding.next": "Siguiente",
        "onboarding.get_started": "Comenzar",

        // Common
        "common.cancel": "Cancelar",
        "common.done": "Listo",
        "common.delete": "Eliminar",
        "common.save": "Guardar",
        "common.back": "Atrás",
        "common.confirm": "Confirmar",
        "common.upgrade": "Mejorar",
        "common.loading": "Cargando…",

        // Tier gating
        "tier.locked_reason.quickLink": "Notificar + Enlace Rápido es una función Pro",
        "tier.locked_reason.stewardActs": "Steward Actúa es una función Premium",
    ]

    // MARK: - Korean

    static let ko: [String: String] = [
        // Tabs
        "tab.watches": "감시",
        "tab.savings": "절약",
        "savings.potential_label": "잠재적 절약",
        "savings.community_header": "Steward 사용자들이 크게 절약하고 있어요!",
        "tab.activity": "활동",
        "tab.settings": "설정",

        // Home Screen
        "home.title": "감시",
        "home.subtitle": "Steward가 대신 감시해 드립니다",
        "home.app_title": "Steward",
        "home.app_subtitle": "나만의 AI 컨시어지",
        "home.notifications": "알림",
        "home.chat_prompt": "Steward에게 감시할 항목을 요청하세요…",
        "home.view_all_savings": "전체 절약 보기",
        "home.price_insights": "가격 분석",
        "home.price_insights.tracking": "%d개 가격 추적 중 · 탭하여 딜 보기",
        "home.price_insights.locked": "Pro로 업그레이드하여 딜과 가격 추세를 확인하세요",
        "home.price_insights.pro": "PRO",
        "home.active_watches": "활성 감시",
        "home.edit": "편집",
        "home.done": "완료",
        "home.empty.title": "아직 감시 항목이 없습니다",
        "home.empty.subtitle": "Steward에게 무엇을 모니터링할지 알려주면\n24시간 웹을 감시해 드립니다.",
        "home.add_watch": "Steward AI로 새 감시 추가",
        "home.delete_watch": "감시 삭제",
        "home.select_all": "전체 선택",
        "home.deselect_all": "전체 해제",
        "home.delete_count": "삭제 (%d)",
        "home.delete_confirm": "%d개 감시를 삭제하시겠습니까?",
        "home.delete_warning": "이 작업은 되돌릴 수 없습니다.",
        "home.triggered.cart": "장바구니에 추가 가능",
        "home.triggered.book": "예약 가능",
        "home.triggered.price": "목표 가격 도달",
        "home.triggered.form": "제출 준비 완료",
        "home.triggered.notify": "변경 감지됨",
        "home.review": "확인하기 →",
        "home.savings.title": "잠재적 절약",
        "home.filter.all": "전체",
        "home.filter.active": "활성",
        "home.filter.triggered": "발동됨",
        "home.filter.paused": "일시정지",

        // Activity Screen
        "activity.title": "활동",
        "activity.subtitle": "Steward가 처리한 모든 것",
        "activity.empty.title": "아직 활동이 없습니다",
        "activity.empty.subtitle": "Steward가 대신 행동하면\n여기에 타임라인이 표시됩니다.",
        "activity.empty.filtered": "이 필터에 맞는 활동이\n여기에 표시됩니다.",
        "activity.filter.all": "전체",
        "activity.filter.lifecycle": "생명주기",
        "activity.filter.actions": "액션",
        "activity.filter.alerts": "알림",
        "activity.steward_at_work": "Steward 작업 중",
        "activity.past_7_days": "지난 7일",
        "activity.loading_stats": "통계 로딩 중…",
        "activity.no_watches": "감시를 만들면 Steward가 일하기 시작합니다.",
        "activity.weekly_checks": "이번 주 Steward가 **%@회** 감시를 확인했습니다.",
        "activity.monitoring": "Steward가 %d개의 %@을(를) 모니터링 중입니다. 확인 결과가 곧 여기에 표시됩니다.",
        "activity.check": "확인",
        "activity.checks": "확인",
        "activity.trigger": "발동",
        "activity.triggers": "발동",
        "activity.action": "액션",
        "activity.actions": "액션",
        "activity.watch": "감시",
        "activity.watches": "감시",
        "activity.time": "번",
        "activity.times": "번",

        // Settings Screen
        "settings.title": "설정",
        "settings.subtitle": "Steward 맞춤 설정",
        "settings.appearance": "외관",
        "settings.dark_mode": "다크 모드",
        "settings.notifications": "알림",
        "settings.push": "푸시 알림",
        "settings.quiet_hours": "방해 금지 시간",
        "settings.quiet_hours.desc": "설정된 시간 동안 알림 끄기",
        "settings.from": "시작",
        "settings.to": "~",
        "settings.watch_defaults": "감시 기본값",
        "settings.default_frequency": "기본 주기",
        "settings.when_triggered": "발동 시",
        "settings.when_triggered.desc": "새 감시의 기본값",
        "settings.currency": "통화",
        "settings.language": "언어",
        "settings.account": "계정",
        "settings.plan": "플랜",
        "settings.restore": "구매 복원",
        "settings.replay_tour": "환영 투어 다시 보기",
        "settings.privacy": "개인정보 처리방침",
        "settings.terms": "이용약관",
        "settings.sign_out": "로그아웃",
        "settings.apple_id": "Apple ID 계정",

        // Detail Screen
        "detail.back": "뒤로",
        "detail.rename": "이름 변경",
        "detail.rename_title": "감시 이름 변경",
        "detail.rename_placeholder": "감시 이름",
        "detail.rename_message": "이 감시의 새 이름을 입력하세요.",
        "detail.delete_confirm": "\"%@\"을(를) 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
        "detail.status.triggered": "변경 감지됨 · 행동 준비 완료",
        "detail.status.attention": "주의 필요 · %d회 실패",
        "detail.status.watching": "감시 중 · %@",
        "detail.price_history": "가격 기록",
        "detail.loading_prices": "가격 데이터 로딩 중...",
        "detail.waiting_prices": "가격 데이터 대기 중",
        "detail.waiting_prices.desc": "Steward가 다음 감시에서 가격 추적을 시작합니다. 데이터가 수집되면 여기에 가격 기록이 표시됩니다.",
        "detail.change_detected": "변경 감지됨",
        "detail.needs_attention": "주의 필요",
        "detail.trouble_checking": "이 감시에서 페이지 확인에 문제가 있습니다.",
        "detail.failed_count": "연속 %d회 실패했습니다. 페이지가 변경되었거나 URL이 더 이상 작동하지 않을 수 있습니다.",
        "detail.ask_ai_fix": "AI에게 수정 요청",
        "detail.find_link": "링크 찾기",
        "detail.action_link": "액션 링크",
        "detail.watching_for": "감시 대상",
        "detail.ai_will": "AI 동작",
        "detail.watch_frequency": "감시 주기",
        "detail.watch_start_time": "감시 시작 시간",
        "detail.next_watch": "다음 감시",
        "detail.notify_via": "알림 방법",
        "detail.not_set": "미설정",
        "detail.condition_met_action": "조건이 충족되었습니다 · 탭하여 %@",
        "detail.condition_met": "조건이 충족되었습니다 · Steward가 지금 행동할 수 있습니다",
        "detail.let_steward_act": "Steward가 지금 행동하도록 하기",
        "detail.no_results": "아직 결과 없음. Steward가 곧 모니터링을 시작합니다",
        "detail.when_triggered": "발동 시 동작",
        "detail.notify_me": "알림만",
        "detail.notify_quick_link": "알림 + 빠른 링크",
        "detail.steward_acts": "Steward 자동 실행",
        "detail.beta": "베타",
        "detail.premium": "프리미엄",
        "detail.only_act_under": "다음 금액 미만일 때만",
        "detail.no_limit": "제한 없음",
        "detail.waiting": "⏳ 발동 대기 중…",
        "detail.delete_watch": "감시 삭제",
        "detail.visit_website": "웹사이트 방문",
        "detail.copy_url": "URL 복사",
        "detail.share_watch": "감시 공유",
        "detail.share_watch.desc": "친구를 초대하여 함께 감시하세요",
        "detail.watch_history": "감시 기록",
        "detail.no_change": "변경 없음",

        // Chat
        "chat.initial": "안녕하세요! 👋 저는 Steward, 당신의 개인 웹 감시자입니다. 웹사이트를 모니터링하고 대신 행동합니다. 무엇을 도와드릴까요?",
        "chat.suggestion.price": "가격 하락 추적",
        "chat.suggestion.restock": "재입고 감시",
        "chat.suggestion.tickets": "티켓이나 예약 찾기",
        "chat.suggestion.booking": "예약 모니터링",
        "chat.placeholder": "감시할 내용을 설명하세요…",

        // Savings
        "savings.title": "잠재적 절약",
        "savings.subtitle": "Steward가 가격 하락을 감지했어요",
        "savings.price_changes": "가격 변동",
        "savings.sort.newest": "최신순",
        "savings.sort.oldest": "오래된 순",
        "savings.sort.biggest": "최대 절약순",
        "savings.sort.name": "감시 이름순",
        "savings.empty.title": "아직 가격 변동이 없습니다",
        "savings.empty.subtitle": "Steward가 감시 항목에서 가격 변동을\n감지하면 여기에 표시됩니다.",

        // Watch Card
        "watch.tracking_stores": "여러 매장에서 추적 중",
        "watch.change_detected": "변경 감지됨!",
        "watch.needs_attention": "주의 필요",

        // Action Modal
        "action.title.price": "목표 가격에 도달했습니다!",
        "action.title.cart": "상품을 구매할 수 있습니다!",
        "action.title.book": "예약 가능한 자리를 찾았습니다!",
        "action.title.form": "제출 준비 완료!",
        "action.title.notify": "변경이 감지되었습니다!",
        "action.done.price": "할인 페이지 열림!",
        "action.done.cart": "상품 페이지 열림!",
        "action.done.book": "예약 페이지 열림!",
        "action.done.form": "양식 페이지 열림!",
        "action.done.notify": "변경 확인됨!",
        "action.tap_to_act": "아래를 탭하여 페이지를 열고 액션을 완료하세요",
        "action.condition_met": "감시 중인 조건이 충족되었습니다",
        "action.page": "페이지",
        "action.change": "변경 감지됨",
        "action.action": "액션",
        "action.copied": "복사됨!",
        "action.promo_detected": "프로모션 코드 감지됨",
        "action.not_now": "나중에",
        "action.got_it": "확인",
        "action.working": "Steward가 작업 중…",
        "action.completing": "대신 액션을 수행하고 있습니다",
        "action.back_home": "홈으로 돌아가기",
        "action.steward_suggests": "Steward 추천",
        "action.suggest.restock": "향후 재입고 감시하기",
        "action.suggest.price_drops": "가격 하락 추적하기",
        "action.suggest.deeper": "더 큰 하락을 계속 감시하기",
        "action.suggest.restock_cart": "재입고도 함께 감시하기",
        "action.suggest.earlier_slot": "더 이른 시간대 감시하기",
        "action.suggest.keep_watching": "변경 사항을 계속 감시하기",

        // Onboarding
        "onboarding.skip": "건너뛰기",
        "onboarding.next": "다음",
        "onboarding.get_started": "시작하기",

        // Common
        "common.cancel": "취소",
        "common.done": "완료",
        "common.delete": "삭제",
        "common.save": "저장",
        "common.back": "뒤로",
        "common.confirm": "확인",
        "common.upgrade": "업그레이드",
        "common.loading": "로딩 중…",

        // Tier gating
        "tier.locked_reason.quickLink": "알림 + 빠른 링크는 Pro 기능입니다",
        "tier.locked_reason.stewardActs": "Steward 자동 실행은 Premium 기능입니다",
    ]

    // MARK: - Chinese (Simplified)

    static let zhHans: [String: String] = [
        // Tabs
        "tab.watches": "监控",
        "tab.savings": "节省",
        "savings.potential_label": "潜在节省",
        "savings.community_header": "Steward 用户们正在省大钱！",
        "tab.activity": "活动",
        "tab.settings": "设置",

        // Home Screen
        "home.title": "监控",
        "home.subtitle": "Steward 替你监控，让你不必操心",
        "home.app_title": "Steward",
        "home.app_subtitle": "你的私人 AI 管家",
        "home.notifications": "通知",
        "home.chat_prompt": "让 Steward 帮你监控…",
        "home.view_all_savings": "查看全部节省",
        "home.price_insights": "价格分析",
        "home.price_insights.tracking": "正在追踪 %d 个价格 · 点击查看优惠",
        "home.price_insights.locked": "升级到 Pro 查看优惠和价格趋势",
        "home.price_insights.pro": "PRO",
        "home.active_watches": "活跃监控",
        "home.edit": "编辑",
        "home.done": "完成",
        "home.empty.title": "还没有监控项",
        "home.empty.subtitle": "告诉 Steward 要监控什么，\n它会全天候为你监控网页。",
        "home.add_watch": "通过 Steward AI 添加新监控",
        "home.delete_watch": "删除监控",
        "home.select_all": "全选",
        "home.deselect_all": "取消全选",
        "home.delete_count": "删除 (%d)",
        "home.delete_confirm": "删除 %d 个监控？",
        "home.delete_warning": "此操作无法撤销。",
        "home.triggered.cart": "可以加入购物车",
        "home.triggered.book": "可以预订",
        "home.triggered.price": "已达目标价格",
        "home.triggered.form": "可以提交",
        "home.triggered.notify": "检测到变化",
        "home.review": "查看 →",
        "home.savings.title": "潜在节省",
        "home.filter.all": "全部",
        "home.filter.active": "活跃",
        "home.filter.triggered": "已触发",
        "home.filter.paused": "已暂停",

        // Activity Screen
        "activity.title": "活动",
        "activity.subtitle": "Steward 为你处理的所有事项",
        "activity.empty.title": "暂无活动",
        "activity.empty.subtitle": "当 Steward 代你行动时，\n你会在这里看到完整时间线。",
        "activity.empty.filtered": "符合此筛选条件的活动\n将显示在这里。",
        "activity.filter.all": "全部",
        "activity.filter.lifecycle": "生命周期",
        "activity.filter.actions": "操作",
        "activity.filter.alerts": "警报",
        "activity.steward_at_work": "Steward 工作中",
        "activity.past_7_days": "过去7天",
        "activity.loading_stats": "正在加载统计…",
        "activity.no_watches": "创建一个监控，Steward 将开始为你工作。",
        "activity.monitoring": "Steward 正在监控 %d 个%@。检查结果将很快显示在这里。",
        "activity.weekly_checks": "本周 Steward 替你检查了 **%@次**，让你无需亲自操心。",
        "activity.check": "次检查",
        "activity.checks": "次检查",
        "activity.trigger": "次触发",
        "activity.triggers": "次触发",
        "activity.action": "个操作",
        "activity.actions": "个操作",
        "activity.watch": "个监控",
        "activity.watches": "个监控",
        "activity.time": "次",
        "activity.times": "次",

        // Settings Screen
        "settings.title": "设置",
        "settings.subtitle": "个性化 Steward 的服务方式",
        "settings.appearance": "外观",
        "settings.dark_mode": "深色模式",
        "settings.notifications": "通知",
        "settings.push": "推送通知",
        "settings.quiet_hours": "免打扰时间",
        "settings.quiet_hours.desc": "在设定时间内静音通知",
        "settings.from": "从",
        "settings.to": "到",
        "settings.watch_defaults": "监控默认值",
        "settings.default_frequency": "默认频率",
        "settings.when_triggered": "触发时",
        "settings.when_triggered.desc": "新监控的默认设置",
        "settings.currency": "货币",
        "settings.language": "语言",
        "settings.account": "账户",
        "settings.plan": "套餐",
        "settings.restore": "恢复购买",
        "settings.replay_tour": "重播欢迎导览",
        "settings.privacy": "隐私政策",
        "settings.terms": "服务条款",
        "settings.sign_out": "退出登录",
        "settings.apple_id": "Apple ID 账户",

        // Detail Screen
        "detail.back": "返回",
        "detail.rename": "重命名",
        "detail.rename_title": "重命名监控",
        "detail.rename_placeholder": "监控名称",
        "detail.rename_message": "为这个监控输入新名称。",
        "detail.delete_confirm": "确定要删除「%@」吗？此操作无法撤销。",
        "detail.status.triggered": "检测到变化 · 准备执行",
        "detail.status.attention": "需要注意 · %d 次失败",
        "detail.status.watching": "监控中 · %@",
        "detail.price_history": "价格历史",
        "detail.loading_prices": "正在加载价格数据...",
        "detail.waiting_prices": "等待价格数据",
        "detail.waiting_prices.desc": "Steward 将在下次监控时开始追踪价格。随着数据的收集，价格历史将显示在这里。",
        "detail.change_detected": "检测到变化",
        "detail.needs_attention": "需要注意",
        "detail.trouble_checking": "此监控在检查页面时遇到问题。",
        "detail.failed_count": "已连续失败 %d 次。页面可能已更改或 URL 可能已失效。",
        "detail.ask_ai_fix": "让 AI 修复",
        "detail.find_link": "查找链接",
        "detail.action_link": "操作链接",
        "detail.watching_for": "监控目标",
        "detail.ai_will": "AI 将",
        "detail.watch_frequency": "监控频率",
        "detail.watch_start_time": "监控开始时间",
        "detail.next_watch": "下次监控",
        "detail.notify_via": "通知方式",
        "detail.not_set": "未设置",
        "detail.condition_met_action": "条件已满足 · 点击%@",
        "detail.condition_met": "条件已满足 · Steward 可以立即执行",
        "detail.let_steward_act": "让 Steward 立即执行",
        "detail.no_results": "暂无结果。Steward 将很快开始监控",
        "detail.when_triggered": "触发时动作",
        "detail.notify_me": "仅通知",
        "detail.notify_quick_link": "通知 + 快捷链接",
        "detail.steward_acts": "Steward 自动执行",
        "detail.beta": "测试版",
        "detail.premium": "高级版",
        "detail.only_act_under": "仅在低于此金额时执行",
        "detail.no_limit": "无限制",
        "detail.waiting": "⏳ 等待触发…",
        "detail.delete_watch": "删除监控",
        "detail.visit_website": "访问网站",
        "detail.copy_url": "复制链接",
        "detail.share_watch": "分享监控",
        "detail.share_watch.desc": "邀请朋友一起监控",
        "detail.watch_history": "监控历史",
        "detail.no_change": "未检测到变化",

        // Chat
        "chat.initial": "你好！👋 我是 Steward，你的个人网页监控助手。我帮你监控网站并代你行动。有什么可以帮你的吗？",
        "chat.suggestion.price": "追踪降价",
        "chat.suggestion.restock": "监控补货",
        "chat.suggestion.tickets": "查找门票或预约",
        "chat.suggestion.booking": "监控预订",
        "chat.placeholder": "描述你想监控的内容…",

        // Savings
        "savings.title": "潜在节省",
        "savings.subtitle": "Steward 为您追踪到的降价",
        "savings.price_changes": "价格变动",
        "savings.sort.newest": "最新",
        "savings.sort.oldest": "最早",
        "savings.sort.biggest": "最大节省",
        "savings.sort.name": "监控名称",
        "savings.empty.title": "暂无价格变动",
        "savings.empty.subtitle": "当 Steward 检测到你的监控项\n价格变动时，它们将显示在这里。",

        // Watch Card
        "watch.tracking_stores": "跨店追踪中",
        "watch.change_detected": "检测到变化！",
        "watch.needs_attention": "需要注意",

        // Action Modal
        "action.title.price": "已达目标价格！",
        "action.title.cart": "商品有货了！",
        "action.title.book": "找到空位了！",
        "action.title.form": "可以提交了！",
        "action.title.notify": "检测到变化！",
        "action.done.price": "优惠页面已打开！",
        "action.done.cart": "商品页面已打开！",
        "action.done.book": "预订页面已打开！",
        "action.done.form": "表单页面已打开！",
        "action.done.notify": "变化已确认！",
        "action.tap_to_act": "点击下方打开页面并完成操作",
        "action.condition_met": "你监控的条件已满足",
        "action.page": "页面",
        "action.change": "检测到变化",
        "action.action": "操作",
        "action.copied": "已复制！",
        "action.promo_detected": "检测到促销码",
        "action.not_now": "稍后再说",
        "action.got_it": "知道了",
        "action.working": "Steward 正在处理…",
        "action.completing": "正在代你完成操作",
        "action.back_home": "返回首页",
        "action.steward_suggests": "Steward 建议",
        "action.suggest.restock": "监控未来补货",
        "action.suggest.price_drops": "追踪降价",
        "action.suggest.deeper": "继续监控更大幅度的降价",
        "action.suggest.restock_cart": "同时监控补货",
        "action.suggest.earlier_slot": "监控更早的时段",
        "action.suggest.keep_watching": "继续监控变化",

        // Onboarding
        "onboarding.skip": "跳过",
        "onboarding.next": "下一步",
        "onboarding.get_started": "开始使用",

        // Common
        "common.cancel": "取消",
        "common.done": "完成",
        "common.delete": "删除",
        "common.save": "保存",
        "common.back": "返回",
        "common.confirm": "确认",
        "common.upgrade": "升级",
        "common.loading": "加载中…",

        // Tier gating
        "tier.locked_reason.quickLink": "通知 + 快速链接是 Pro 功能",
        "tier.locked_reason.stewardActs": "Steward 自动执行是 Premium 功能",
    ]

    // MARK: - Vietnamese

    static let vi: [String: String] = [
        // Tabs
        "tab.watches": "Theo dõi",
        "tab.savings": "Tiết kiệm",
        "savings.potential_label": "Tiết kiệm tiềm năng",
        "savings.community_header": "Người dùng Steward đang tiết kiệm lớn!",
        "tab.activity": "Hoạt động",
        "tab.settings": "Cài đặt",

        // Home Screen
        "home.title": "Theo dõi",
        "home.subtitle": "Steward theo dõi để bạn không cần phải lo",
        "home.app_title": "Steward",
        "home.app_subtitle": "Trợ lý AI cá nhân của bạn",
        "home.notifications": "Thông báo",
        "home.chat_prompt": "Nhờ Steward theo dõi điều gì đó…",
        "home.view_all_savings": "Xem tất cả tiết kiệm",
        "home.price_insights": "Phân tích giá",
        "home.price_insights.tracking": "Đang theo dõi %d giá · Nhấn để xem ưu đãi",
        "home.price_insights.locked": "Nâng cấp Pro để xem ưu đãi và xu hướng giá",
        "home.price_insights.pro": "PRO",
        "home.active_watches": "Đang theo dõi",
        "home.edit": "Sửa",
        "home.done": "Xong",
        "home.empty.title": "Chưa có mục theo dõi",
        "home.empty.subtitle": "Cho Steward biết cần giám sát gì và nó sẽ\ntheo dõi web cho bạn suốt ngày đêm.",
        "home.add_watch": "Thêm mục theo dõi qua Steward AI",
        "home.delete_watch": "Xóa theo dõi",
        "home.select_all": "Chọn tất cả",
        "home.deselect_all": "Bỏ chọn tất cả",
        "home.delete_count": "Xóa (%d)",
        "home.delete_confirm": "Xóa %d mục theo dõi?",
        "home.delete_warning": "Hành động này không thể hoàn tác.",
        "home.triggered.cart": "SẴN SÀNG THÊM VÀO GIỎ",
        "home.triggered.book": "SẴN SÀNG ĐẶT CHỖ",
        "home.triggered.price": "ĐÃ ĐẠT GIÁ MỤC TIÊU",
        "home.triggered.form": "SẴN SÀNG GỬI",
        "home.triggered.notify": "PHÁT HIỆN THAY ĐỔI",
        "home.review": "Xem xét →",
        "home.savings.title": "Tiết kiệm tiềm năng",
        "home.filter.all": "Tất cả",
        "home.filter.active": "Đang hoạt động",
        "home.filter.triggered": "Đã kích hoạt",
        "home.filter.paused": "Tạm dừng",

        // Activity Screen
        "activity.title": "Hoạt động",
        "activity.subtitle": "Mọi thứ Steward đã xử lý cho bạn",
        "activity.empty.title": "Chưa có hoạt động",
        "activity.empty.subtitle": "Khi Steward hành động thay bạn,\nbạn sẽ thấy dòng thời gian ở đây.",
        "activity.empty.filtered": "Hoạt động phù hợp bộ lọc này\nsẽ xuất hiện ở đây.",
        "activity.filter.all": "Tất cả",
        "activity.filter.lifecycle": "Vòng đời",
        "activity.filter.actions": "Hành động",
        "activity.filter.alerts": "Cảnh báo",
        "activity.steward_at_work": "Steward Đang Làm Việc",
        "activity.past_7_days": "7 ngày qua",
        "activity.loading_stats": "Đang tải thống kê…",
        "activity.no_watches": "Tạo một mục theo dõi và Steward sẽ bắt đầu làm việc cho bạn.",
        "activity.monitoring": "Steward đang giám sát %d %@. Kết quả kiểm tra sẽ sớm xuất hiện ở đây.",
        "activity.weekly_checks": "Steward đã kiểm tra các mục theo dõi **%@ %@** tuần này thay cho bạn.",
        "activity.check": "lần kiểm tra",
        "activity.checks": "lần kiểm tra",
        "activity.trigger": "lần kích hoạt",
        "activity.triggers": "lần kích hoạt",
        "activity.action": "hành động",
        "activity.actions": "hành động",
        "activity.watch": "mục theo dõi",
        "activity.watches": "mục theo dõi",
        "activity.time": "lần",
        "activity.times": "lần",

        // Settings Screen
        "settings.title": "Cài đặt",
        "settings.subtitle": "Tùy chỉnh cách Steward phục vụ bạn",
        "settings.appearance": "Giao diện",
        "settings.dark_mode": "Chế độ tối",
        "settings.notifications": "Thông báo",
        "settings.push": "Thông báo đẩy",
        "settings.quiet_hours": "Giờ yên tĩnh",
        "settings.quiet_hours.desc": "Tắt tiếng thông báo trong giờ đã đặt",
        "settings.from": "Từ",
        "settings.to": "đến",
        "settings.watch_defaults": "Mặc định theo dõi",
        "settings.default_frequency": "Tần suất mặc định",
        "settings.when_triggered": "Khi kích hoạt",
        "settings.when_triggered.desc": "Mặc định cho mục theo dõi mới",
        "settings.currency": "Tiền tệ",
        "settings.language": "Ngôn ngữ",
        "settings.account": "Tài khoản",
        "settings.plan": "Gói",
        "settings.restore": "Khôi phục mua hàng",
        "settings.replay_tour": "Xem lại hướng dẫn",
        "settings.privacy": "Chính sách bảo mật",
        "settings.terms": "Điều khoản dịch vụ",
        "settings.sign_out": "Đăng xuất",
        "settings.apple_id": "Tài khoản Apple ID",

        // Detail Screen
        "detail.back": "Quay lại",
        "detail.rename": "Đổi tên",
        "detail.rename_title": "Đổi tên theo dõi",
        "detail.rename_placeholder": "Tên theo dõi",
        "detail.rename_message": "Nhập tên mới cho mục theo dõi này.",
        "detail.delete_confirm": "Bạn có chắc muốn xóa \"%@\" không? Hành động này không thể hoàn tác.",
        "detail.status.triggered": "Phát hiện thay đổi · Sẵn sàng hành động",
        "detail.status.attention": "Cần chú ý · %d lần thất bại",
        "detail.status.watching": "Đang theo dõi · %@",
        "detail.price_history": "Lịch sử giá",
        "detail.loading_prices": "Đang tải dữ liệu giá...",
        "detail.waiting_prices": "Đang chờ dữ liệu giá",
        "detail.waiting_prices.desc": "Steward sẽ bắt đầu theo dõi giá trong lần kiểm tra tiếp theo. Lịch sử giá sẽ hiển thị ở đây khi có dữ liệu.",
        "detail.change_detected": "PHÁT HIỆN THAY ĐỔI",
        "detail.needs_attention": "CẦN CHÚ Ý",
        "detail.trouble_checking": "Mục theo dõi này đang gặp sự cố khi kiểm tra trang.",
        "detail.failed_count": "Đã thất bại %d lần liên tiếp. Trang có thể đã thay đổi hoặc URL không còn hoạt động.",
        "detail.ask_ai_fix": "Nhờ AI sửa",
        "detail.find_link": "Tìm liên kết",
        "detail.action_link": "Liên kết hành động",
        "detail.watching_for": "Đang theo dõi",
        "detail.ai_will": "AI sẽ",
        "detail.watch_frequency": "Tần suất theo dõi",
        "detail.watch_start_time": "Thời gian bắt đầu",
        "detail.next_watch": "Lần theo dõi tiếp",
        "detail.notify_via": "Thông báo qua",
        "detail.not_set": "Chưa đặt",
        "detail.condition_met_action": "Điều kiện đã đạt · Nhấn để %@",
        "detail.condition_met": "Điều kiện đã đạt · Steward có thể hành động ngay",
        "detail.let_steward_act": "Để Steward hành động ngay",
        "detail.no_results": "Chưa có kết quả. Steward sẽ sớm bắt đầu giám sát",
        "detail.when_triggered": "Khi Kích Hoạt",
        "detail.notify_me": "Chỉ thông báo",
        "detail.notify_quick_link": "Thông báo + Liên kết nhanh",
        "detail.steward_acts": "Steward Tự Thực Hiện",
        "detail.beta": "Beta",
        "detail.premium": "Premium",
        "detail.only_act_under": "Chỉ thực hiện khi dưới",
        "detail.no_limit": "Không giới hạn",
        "detail.waiting": "⏳ Đang chờ kích hoạt…",
        "detail.delete_watch": "Xóa Theo Dõi",
        "detail.visit_website": "Truy cập trang web",
        "detail.copy_url": "Sao chép URL",
        "detail.share_watch": "Chia sẻ theo dõi",
        "detail.share_watch.desc": "Mời bạn bè cùng theo dõi",
        "detail.watch_history": "Lịch sử theo dõi",
        "detail.no_change": "Không phát hiện thay đổi",

        // Chat
        "chat.initial": "Xin chào! 👋 Tôi là Steward, trợ lý theo dõi web cá nhân của bạn. Tôi giám sát trang web và hành động thay bạn. Bạn cần giúp gì?",
        "chat.suggestion.price": "Theo dõi giảm giá",
        "chat.suggestion.restock": "Theo dõi hàng về",
        "chat.suggestion.tickets": "Tìm vé hoặc lịch hẹn",
        "chat.suggestion.booking": "Theo dõi đặt chỗ",
        "chat.placeholder": "Mô tả điều bạn muốn theo dõi…",

        // Savings
        "savings.title": "Tiết kiệm tiềm năng",
        "savings.subtitle": "Giá mà Steward phát hiện giảm cho bạn",
        "savings.price_changes": "Biến động giá",
        "savings.sort.newest": "Mới nhất",
        "savings.sort.oldest": "Cũ nhất",
        "savings.sort.biggest": "Tiết kiệm nhiều nhất",
        "savings.sort.name": "Tên theo dõi",
        "savings.empty.title": "Chưa có biến động giá",
        "savings.empty.subtitle": "Khi Steward phát hiện biến động giá\ntrong các mục theo dõi, chúng sẽ hiển thị ở đây.",

        // Watch Card
        "watch.tracking_stores": "Đang theo dõi nhiều cửa hàng",
        "watch.change_detected": "Phát hiện thay đổi!",
        "watch.needs_attention": "Cần chú ý",

        // Action Modal
        "action.title.price": "Đã đạt giá mục tiêu!",
        "action.title.cart": "Sản phẩm đã có hàng!",
        "action.title.book": "Đã tìm thấy chỗ trống!",
        "action.title.form": "Sẵn sàng gửi!",
        "action.title.notify": "Phát hiện thay đổi!",
        "action.done.price": "Đã mở trang ưu đãi!",
        "action.done.cart": "Đã mở trang sản phẩm!",
        "action.done.book": "Đã mở trang đặt chỗ!",
        "action.done.form": "Đã mở trang biểu mẫu!",
        "action.done.notify": "Đã xác nhận thay đổi!",
        "action.tap_to_act": "Nhấn bên dưới để mở trang và hoàn tất hành động",
        "action.condition_met": "Điều kiện theo dõi của bạn đã được đáp ứng",
        "action.page": "Trang",
        "action.change": "Phát hiện thay đổi",
        "action.action": "Hành động",
        "action.copied": "Đã sao chép!",
        "action.promo_detected": "Phát hiện mã khuyến mãi",
        "action.not_now": "Để sau",
        "action.got_it": "Đã hiểu",
        "action.working": "Steward đang xử lý…",
        "action.completing": "Đang thực hiện hành động thay bạn",
        "action.back_home": "Về trang chủ",
        "action.steward_suggests": "Steward gợi ý",
        "action.suggest.restock": "Theo dõi hàng về trong tương lai",
        "action.suggest.price_drops": "Theo dõi giảm giá",
        "action.suggest.deeper": "Tiếp tục theo dõi giảm giá sâu hơn",
        "action.suggest.restock_cart": "Theo dõi hàng về luôn",
        "action.suggest.earlier_slot": "Theo dõi khung giờ sớm hơn",
        "action.suggest.keep_watching": "Tiếp tục theo dõi thay đổi",

        // Onboarding
        "onboarding.skip": "Bỏ qua",
        "onboarding.next": "Tiếp",
        "onboarding.get_started": "Bắt đầu",

        // Common
        "common.cancel": "Hủy",
        "common.done": "Xong",
        "common.delete": "Xóa",
        "common.save": "Lưu",
        "common.back": "Quay lại",
        "common.confirm": "Xác nhận",
        "common.upgrade": "Nâng cấp",
        "common.loading": "Đang tải…",

        // Tier gating
        "tier.locked_reason.quickLink": "Thông báo + Liên kết nhanh là tính năng Pro",
        "tier.locked_reason.stewardActs": "Steward Tự động là tính năng Premium",
    ]

    // MARK: - French

    static let fr: [String: String] = [
        // Tabs
        "tab.watches": "Surveillances",
        "tab.savings": "Économies",
        "savings.potential_label": "Économies potentielles",
        "savings.community_header": "Les Stewards font de grosses économies !",
        "tab.activity": "Activité",
        "tab.settings": "Réglages",

        // Home Screen
        "home.title": "Surveillances",
        "home.subtitle": "Steward surveille pour que vous n'ayez pas à le faire",
        "home.app_title": "Steward",
        "home.app_subtitle": "Votre concierge IA personnel",
        "home.notifications": "Notifications",
        "home.chat_prompt": "Demandez à Steward de surveiller quelque chose…",
        "home.view_all_savings": "Voir toutes les économies",
        "home.price_insights": "Analyse des prix",
        "home.price_insights.tracking": "Suivi de %d prix · Appuyez pour voir les offres",
        "home.price_insights.locked": "Passez à Pro pour voir les offres et tendances de prix",
        "home.price_insights.pro": "PRO",
        "home.active_watches": "Surveillances actives",
        "home.edit": "Modifier",
        "home.done": "Terminé",
        "home.empty.title": "Pas encore de surveillance",
        "home.empty.subtitle": "Dites à Steward quoi surveiller et il\nveillera sur le web pour vous jour et nuit.",
        "home.add_watch": "Ajouter une surveillance via Steward AI",
        "home.delete_watch": "Supprimer la surveillance",
        "home.select_all": "Tout sélectionner",
        "home.deselect_all": "Tout désélectionner",
        "home.delete_count": "Supprimer (%d)",
        "home.delete_confirm": "Supprimer %d surveillances ?",
        "home.delete_warning": "Cette action est irréversible.",
        "home.triggered.cart": "PRÊT À AJOUTER AU PANIER",
        "home.triggered.book": "PRÊT À RÉSERVER",
        "home.triggered.price": "PRIX CIBLE ATTEINT",
        "home.triggered.form": "PRÊT À SOUMETTRE",
        "home.triggered.notify": "CHANGEMENT DÉTECTÉ",
        "home.review": "Voir →",
        "home.savings.title": "Économies potentielles",
        "home.filter.all": "Tout",
        "home.filter.active": "Actif",
        "home.filter.triggered": "Déclenché",
        "home.filter.paused": "En pause",

        // Activity Screen
        "activity.title": "Activité",
        "activity.subtitle": "Tout ce que Steward a géré pour vous",
        "activity.empty.title": "Pas encore d'activité",
        "activity.empty.subtitle": "Quand Steward agit pour vous,\nvous verrez tout ici.",
        "activity.empty.filtered": "Les activités correspondant\nà ce filtre apparaîtront ici.",
        "activity.filter.all": "Tout",
        "activity.filter.lifecycle": "Cycle de vie",
        "activity.filter.actions": "Actions",
        "activity.filter.alerts": "Alertes",
        "activity.steward_at_work": "Steward au Travail",
        "activity.past_7_days": "7 derniers jours",
        "activity.loading_stats": "Chargement des stats…",
        "activity.no_watches": "Créez une surveillance et Steward commencera à travailler pour vous.",
        "activity.monitoring": "Steward surveille %d %@. Les vérifications apparaîtront bientôt ici.",
        "activity.weekly_checks": "Steward a vérifié vos surveillances **%@ %@** cette semaine à votre place.",
        "activity.check": "vérification",
        "activity.checks": "vérifications",
        "activity.trigger": "déclenchement",
        "activity.triggers": "déclenchements",
        "activity.action": "action",
        "activity.actions": "actions",
        "activity.watch": "surveillance",
        "activity.watches": "surveillances",
        "activity.time": "fois",
        "activity.times": "fois",

        // Settings Screen
        "settings.title": "Réglages",
        "settings.subtitle": "Personnalisez comment Steward vous sert",
        "settings.appearance": "Apparence",
        "settings.dark_mode": "Mode sombre",
        "settings.notifications": "Notifications",
        "settings.push": "Notifications push",
        "settings.quiet_hours": "Heures calmes",
        "settings.quiet_hours.desc": "Couper les notifications pendant les heures définies",
        "settings.from": "De",
        "settings.to": "à",
        "settings.watch_defaults": "Valeurs par Défaut",
        "settings.default_frequency": "Fréquence par défaut",
        "settings.when_triggered": "Au déclenchement",
        "settings.when_triggered.desc": "Par défaut pour les nouvelles surveillances",
        "settings.currency": "Devise",
        "settings.language": "Langue",
        "settings.account": "Compte",
        "settings.plan": "Forfait",
        "settings.restore": "Restaurer les achats",
        "settings.replay_tour": "Revoir la visite guidée",
        "settings.privacy": "Politique de confidentialité",
        "settings.terms": "Conditions d'utilisation",
        "settings.sign_out": "Déconnexion",
        "settings.apple_id": "Compte Apple ID",

        // Detail Screen
        "detail.back": "Retour",
        "detail.rename": "Renommer",
        "detail.rename_title": "Renommer la surveillance",
        "detail.rename_placeholder": "Nom de la surveillance",
        "detail.rename_message": "Entrez un nouveau nom pour cette surveillance.",
        "detail.delete_confirm": "Voulez-vous vraiment supprimer « %@ » ? Cette action est irréversible.",
        "detail.status.triggered": "Changement détecté · Prêt à agir",
        "detail.status.attention": "Attention requise · %d échecs",
        "detail.status.watching": "Surveillance · %@",
        "detail.price_history": "Historique des prix",
        "detail.loading_prices": "Chargement des données de prix...",
        "detail.waiting_prices": "En attente des données de prix",
        "detail.waiting_prices.desc": "Steward commencera à suivre les prix lors de la prochaine vérification. L'historique des prix apparaîtra ici au fur et à mesure.",
        "detail.change_detected": "CHANGEMENT DÉTECTÉ",
        "detail.needs_attention": "ATTENTION REQUISE",
        "detail.trouble_checking": "Cette surveillance a des difficultés à vérifier la page.",
        "detail.failed_count": "Échoué %d fois de suite. La page a peut-être changé ou l'URL ne fonctionne peut-être plus.",
        "detail.ask_ai_fix": "Demander à l'IA de corriger",
        "detail.find_link": "Trouver le lien",
        "detail.action_link": "Lien d'action",
        "detail.watching_for": "Surveille",
        "detail.ai_will": "L'IA va",
        "detail.watch_frequency": "Fréquence de surveillance",
        "detail.watch_start_time": "Heure de début",
        "detail.next_watch": "Prochaine vérification",
        "detail.notify_via": "Notifier via",
        "detail.not_set": "Non défini",
        "detail.condition_met_action": "Votre condition est remplie · Appuyez pour %@",
        "detail.condition_met": "Votre condition est remplie · Steward peut agir maintenant",
        "detail.let_steward_act": "Laisser Steward agir maintenant",
        "detail.no_results": "Pas encore de résultats. Steward commencera bientôt la surveillance",
        "detail.when_triggered": "Au Déclenchement",
        "detail.notify_me": "Me Notifier",
        "detail.notify_quick_link": "Notifier + Lien Direct",
        "detail.steward_acts": "Steward Agit",
        "detail.beta": "Bêta",
        "detail.premium": "Premium",
        "detail.only_act_under": "Agir seulement si moins de",
        "detail.no_limit": "Sans limite",
        "detail.waiting": "⏳ En attente du déclenchement…",
        "detail.delete_watch": "Supprimer la Surveillance",
        "detail.visit_website": "Visiter le site web",
        "detail.copy_url": "Copier l'URL",
        "detail.share_watch": "Partager la surveillance",
        "detail.share_watch.desc": "Invitez un ami à surveiller aussi",
        "detail.watch_history": "Historique",
        "detail.no_change": "Aucun changement détecté",

        // Chat
        "chat.initial": "Bonjour ! 👋 Je suis Steward, votre assistant de surveillance web personnel. Je surveille les sites et agis en votre nom. Comment puis-je vous aider ?",
        "chat.suggestion.price": "Suivre une baisse de prix",
        "chat.suggestion.restock": "Surveiller un réapprovisionnement",
        "chat.suggestion.tickets": "Trouver des billets ou rendez-vous",
        "chat.suggestion.booking": "Surveiller une réservation",
        "chat.placeholder": "Décrivez ce que vous voulez surveiller…",

        // Savings
        "savings.title": "Économies potentielles",
        "savings.subtitle": "Prix que Steward a détecté en baisse pour vous",
        "savings.price_changes": "Variations de prix",
        "savings.sort.newest": "Plus récents",
        "savings.sort.oldest": "Plus anciens",
        "savings.sort.biggest": "Plus grandes économies",
        "savings.sort.name": "Nom de surveillance",
        "savings.empty.title": "Pas encore de variations de prix",
        "savings.empty.subtitle": "Quand Steward détecte des variations de prix\nsur vos surveillances, elles apparaîtront ici.",

        // Watch Card
        "watch.tracking_stores": "Suivi multi-boutiques",
        "watch.change_detected": "Changement détecté !",
        "watch.needs_attention": "Attention requise",

        // Action Modal
        "action.title.price": "Prix cible atteint !",
        "action.title.cart": "Article disponible !",
        "action.title.book": "Créneau trouvé !",
        "action.title.form": "Prêt à soumettre !",
        "action.title.notify": "Changement détecté !",
        "action.done.price": "Page de l'offre ouverte !",
        "action.done.cart": "Page du produit ouverte !",
        "action.done.book": "Page de réservation ouverte !",
        "action.done.form": "Page du formulaire ouverte !",
        "action.done.notify": "Changement pris en compte !",
        "action.tap_to_act": "Appuyez ci-dessous pour ouvrir la page et finaliser votre action",
        "action.condition_met": "Votre condition surveillée a été remplie",
        "action.page": "Page",
        "action.change": "Changement détecté",
        "action.action": "Action",
        "action.copied": "Copié !",
        "action.promo_detected": "Code promo détecté",
        "action.not_now": "Pas maintenant",
        "action.got_it": "Compris",
        "action.working": "Steward travaille…",
        "action.completing": "Exécution de l'action en votre nom",
        "action.back_home": "Retour à l'accueil",
        "action.steward_suggests": "Steward suggère",
        "action.suggest.restock": "Surveiller les futurs réapprovisionnements",
        "action.suggest.price_drops": "Suivre les baisses de prix",
        "action.suggest.deeper": "Continuer à surveiller une baisse plus importante",
        "action.suggest.restock_cart": "Surveiller aussi les réapprovisionnements",
        "action.suggest.earlier_slot": "Surveiller un créneau plus tôt",
        "action.suggest.keep_watching": "Continuer à surveiller les changements",

        // Onboarding
        "onboarding.skip": "Passer",
        "onboarding.next": "Suivant",
        "onboarding.get_started": "Commencer",

        // Common
        "common.cancel": "Annuler",
        "common.done": "Terminé",
        "common.delete": "Supprimer",
        "common.save": "Enregistrer",
        "common.back": "Retour",
        "common.confirm": "Confirmer",
        "common.upgrade": "Améliorer",
        "common.loading": "Chargement…",

        // Tier gating
        "tier.locked_reason.quickLink": "Notifier + Lien rapide est une fonctionnalité Pro",
        "tier.locked_reason.stewardActs": "Steward Agit est une fonctionnalité Premium",
    ]

    // MARK: - Farsi (Persian)

    static let fa: [String: String] = [
        // Tabs
        "tab.watches": "نظارت‌ها",
        "tab.savings": "صرفه‌جویی",
        "savings.potential_label": "صرفه‌جویی بالقوه",
        "savings.community_header": "کاربران Steward در حال صرفه‌جویی بزرگ هستند!",
        "tab.activity": "فعالیت",
        "tab.settings": "تنظیمات",

        // Home Screen
        "home.title": "نظارت‌ها",
        "home.subtitle": "Steward نظارت می‌کند تا شما نیازی نداشته باشید",
        "home.app_title": "Steward",
        "home.app_subtitle": "دستیار هوشمند شخصی شما",
        "home.notifications": "اعلان‌ها",
        "home.chat_prompt": "از Steward بخواهید چیزی را نظارت کند…",
        "home.view_all_savings": "مشاهده همه صرفه‌جویی‌های بالقوه",
        "home.price_insights": "بینش قیمت",
        "home.price_insights.tracking": "ردیابی %d قیمت · برای مشاهده تخفیف‌ها لمس کنید",
        "home.price_insights.locked": "برای مشاهده تخفیف‌ها و روند قیمت به Pro ارتقا دهید",
        "home.price_insights.pro": "PRO",
        "home.active_watches": "نظارت‌های فعال",
        "home.edit": "ویرایش",
        "home.done": "انجام شد",
        "home.empty.title": "هنوز نظارتی نیست",
        "home.empty.subtitle": "به Steward بگویید چه چیزی را نظارت کند\nو او شبانه‌روزی وب را برای شما زیر نظر می‌گیرد.",
        "home.add_watch": "افزودن نظارت جدید با هوش مصنوعی Steward",
        "home.delete_watch": "حذف نظارت",
        "home.select_all": "انتخاب همه",
        "home.deselect_all": "لغو انتخاب همه",
        "home.delete_count": "حذف (%d)",
        "home.delete_confirm": "حذف %d نظارت؟",
        "home.delete_warning": "این عمل قابل بازگشت نیست.",
        "home.triggered.cart": "آماده افزودن به سبد خرید",
        "home.triggered.book": "آماده رزرو",
        "home.triggered.price": "قیمت هدف رسید",
        "home.triggered.form": "آماده ارسال",
        "home.triggered.notify": "تغییر شناسایی شد",
        "home.review": "بررسی →",
        "home.savings.title": "صرفه‌جویی بالقوه",
        "home.filter.all": "همه",
        "home.filter.active": "فعال",
        "home.filter.triggered": "فعال شده",
        "home.filter.paused": "متوقف شده",

        // Activity Screen
        "activity.title": "فعالیت",
        "activity.subtitle": "همه کارهایی که Steward برای شما انجام داده",
        "activity.empty.title": "هنوز فعالیتی نیست",
        "activity.empty.subtitle": "وقتی Steward از طرف شما اقدام کند،\nجدول زمانی همه چیز اینجا نمایش داده می‌شود.",
        "activity.empty.filtered": "فعالیت‌های مطابق با این فیلتر\nاینجا نمایش داده می‌شوند.",
        "activity.filter.all": "همه",
        "activity.filter.lifecycle": "چرخه عمر",
        "activity.filter.actions": "اقدامات",
        "activity.filter.alerts": "هشدارها",
        "activity.steward_at_work": "Steward در حال کار",
        "activity.past_7_days": "۷ روز گذشته",
        "activity.loading_stats": "بارگذاری آمار…",
        "activity.no_watches": "یک نظارت ایجاد کنید و Steward شروع به کار برای شما می‌کند.",
        "activity.monitoring": "Steward در حال نظارت بر %d %@ است. بررسی‌ها به زودی اینجا نمایش داده می‌شوند.",
        "activity.weekly_checks": "Steward این هفته **%@ %@** نظارت‌های شما را بررسی کرد تا شما نیازی نداشته باشید.",
        "activity.check": "بررسی",
        "activity.checks": "بررسی",
        "activity.trigger": "فعال‌سازی",
        "activity.triggers": "فعال‌سازی",
        "activity.action": "اقدام",
        "activity.actions": "اقدامات",
        "activity.watch": "نظارت",
        "activity.watches": "نظارت",
        "activity.time": "بار",
        "activity.times": "بار",

        // Settings Screen
        "settings.title": "تنظیمات",
        "settings.subtitle": "شخصی‌سازی نحوه خدمت‌رسانی Steward",
        "settings.appearance": "ظاهر",
        "settings.dark_mode": "حالت تاریک",
        "settings.notifications": "اعلان‌ها",
        "settings.push": "اعلان‌های فوری",
        "settings.quiet_hours": "ساعات آرام",
        "settings.quiet_hours.desc": "خاموش کردن اعلان‌ها در ساعات تعیین شده",
        "settings.from": "از",
        "settings.to": "تا",
        "settings.watch_defaults": "پیش‌فرض‌های نظارت",
        "settings.default_frequency": "تناوب پیش‌فرض",
        "settings.when_triggered": "هنگام فعال‌سازی",
        "settings.when_triggered.desc": "پیش‌فرض برای نظارت‌های جدید",
        "settings.currency": "واحد پول",
        "settings.language": "زبان",
        "settings.account": "حساب کاربری",
        "settings.plan": "طرح اشتراک",
        "settings.restore": "بازیابی خریدها",
        "settings.replay_tour": "پخش مجدد تور خوش‌آمدگویی",
        "settings.privacy": "سیاست حفظ حریم خصوصی",
        "settings.terms": "شرایط خدمات",
        "settings.sign_out": "خروج از حساب",
        "settings.apple_id": "حساب Apple ID",

        // Detail Screen
        "detail.back": "بازگشت",
        "detail.rename": "تغییر نام",
        "detail.rename_title": "تغییر نام نظارت",
        "detail.rename_placeholder": "نام نظارت",
        "detail.rename_message": "نام جدیدی برای این نظارت وارد کنید.",
        "detail.delete_confirm": "آیا مطمئنید که می‌خواهید «%@» را حذف کنید؟ این عمل قابل بازگشت نیست.",
        "detail.status.triggered": "تغییر شناسایی شد · آماده اقدام",
        "detail.status.attention": "نیاز به توجه · %d خطا",
        "detail.status.watching": "در حال نظارت · %@",
        "detail.price_history": "تاریخچه قیمت",
        "detail.loading_prices": "بارگذاری داده‌های قیمت...",
        "detail.waiting_prices": "در انتظار داده‌های قیمت",
        "detail.waiting_prices.desc": "Steward در نظارت بعدی شروع به ردیابی قیمت‌ها می‌کند. تاریخچه قیمت با جمع‌آوری داده‌ها اینجا نمایش داده می‌شود.",
        "detail.change_detected": "تغییر شناسایی شده",
        "detail.needs_attention": "نیاز به توجه",
        "detail.trouble_checking": "این نظارت در بررسی صفحه مشکل دارد.",
        "detail.failed_count": "%d بار پشت سر هم ناموفق بود. ممکن است صفحه تغییر کرده یا لینک دیگر کار نکند.",
        "detail.ask_ai_fix": "از هوش مصنوعی بخواهید رفع کند",
        "detail.find_link": "یافتن لینک",
        "detail.action_link": "لینک اقدام",
        "detail.watching_for": "نظارت برای",
        "detail.ai_will": "هوش مصنوعی",
        "detail.watch_frequency": "تناوب نظارت",
        "detail.watch_start_time": "زمان شروع نظارت",
        "detail.next_watch": "نظارت بعدی",
        "detail.notify_via": "اطلاع‌رسانی از طریق",
        "detail.not_set": "تنظیم نشده",
        "detail.condition_met_action": "شرایط شما برآورده شد · برای %@ لمس کنید",
        "detail.condition_met": "شرایط شما برآورده شد · Steward می‌تواند اقدام کند",
        "detail.let_steward_act": "اجازه اقدام به Steward",
        "detail.no_results": "هنوز نتیجه‌ای نیست. Steward به زودی شروع به نظارت می‌کند",
        "detail.when_triggered": "هنگام فعال‌سازی",
        "detail.notify_me": "اطلاع بده",
        "detail.notify_quick_link": "اطلاع + لینک سریع",
        "detail.steward_acts": "اقدام Steward",
        "detail.beta": "بتا",
        "detail.premium": "ویژه",
        "detail.only_act_under": "فقط اقدام کن اگر کمتر از",
        "detail.no_limit": "بدون محدودیت",
        "detail.waiting": "⏳ در انتظار فعال‌سازی…",
        "detail.delete_watch": "حذف نظارت",
        "detail.visit_website": "مشاهده وب‌سایت",
        "detail.copy_url": "کپی لینک",
        "detail.share_watch": "اشتراک‌گذاری این نظارت",
        "detail.share_watch.desc": "دعوت دوستان برای نظارت بر این مورد",
        "detail.watch_history": "تاریخچه نظارت",
        "detail.no_change": "تغییری شناسایی نشد",

        // Chat
        "chat.initial": "سلام! 👋 من Steward هستم، نظارت‌گر شخصی وب شما. وب‌سایت‌ها را زیر نظر می‌گیرم و از طرف شما اقدام می‌کنم. چطور می‌توانم کمک کنم؟",
        "chat.suggestion.price": "ردیابی کاهش قیمت",
        "chat.suggestion.restock": "نظارت بر موجودی مجدد",
        "chat.suggestion.tickets": "یافتن بلیط یا نوبت",
        "chat.suggestion.booking": "نظارت بر رزرو",
        "chat.placeholder": "توصیف کنید چه چیزی را نظارت کنم…",

        // Savings
        "savings.title": "صرفه‌جویی بالقوه",
        "savings.subtitle": "قیمت‌هایی که Steward برای شما کاهش یافته پیدا کرد",
        "savings.price_changes": "تغییرات قیمت",
        "savings.sort.newest": "جدیدترین",
        "savings.sort.oldest": "قدیمی‌ترین",
        "savings.sort.biggest": "بیشترین صرفه‌جویی",
        "savings.sort.name": "نام نظارت",
        "savings.empty.title": "هنوز تغییر قیمتی نیست",
        "savings.empty.subtitle": "وقتی Steward تغییرات قیمت را\nدر نظارت‌های شما شناسایی کند، اینجا نمایش داده می‌شوند.",

        // Watch Card
        "watch.tracking_stores": "ردیابی در فروشگاه‌ها",
        "watch.change_detected": "تغییر شناسایی شد!",
        "watch.needs_attention": "نیاز به توجه",

        // Action Modal
        "action.title.price": "قیمت هدف رسید!",
        "action.title.cart": "محصول موجود شد!",
        "action.title.book": "وقت پیدا شد!",
        "action.title.form": "آماده ارسال!",
        "action.title.notify": "تغییر شناسایی شد!",
        "action.done.price": "صفحه تخفیف باز شد!",
        "action.done.cart": "صفحه محصول باز شد!",
        "action.done.book": "صفحه رزرو باز شد!",
        "action.done.form": "صفحه فرم باز شد!",
        "action.done.notify": "تغییر تأیید شد!",
        "action.tap_to_act": "برای باز کردن صفحه و تکمیل اقدام، لمس کنید",
        "action.condition_met": "شرایط نظارت شما برآورده شده است",
        "action.page": "صفحه",
        "action.change": "تغییر شناسایی شد",
        "action.action": "اقدام",
        "action.copied": "کپی شد!",
        "action.promo_detected": "کد تخفیف شناسایی شد",
        "action.not_now": "الان نه",
        "action.got_it": "متوجه شدم",
        "action.working": "Steward در حال کار است…",
        "action.completing": "تکمیل اقدام از طرف شما",
        "action.back_home": "بازگشت به خانه",
        "action.steward_suggests": "پیشنهاد Steward",
        "action.suggest.restock": "نظارت بر موجودی‌های آینده",
        "action.suggest.price_drops": "ردیابی کاهش قیمت‌ها",
        "action.suggest.deeper": "ادامه نظارت برای کاهش بیشتر",
        "action.suggest.restock_cart": "نظارت بر موجودی مجدد هم",
        "action.suggest.earlier_slot": "نظارت بر وقت زودتر",
        "action.suggest.keep_watching": "ادامه نظارت بر تغییرات",

        // Onboarding
        "onboarding.skip": "رد شدن",
        "onboarding.next": "بعدی",
        "onboarding.get_started": "شروع کنید",

        // Common
        "common.cancel": "لغو",
        "common.done": "انجام شد",
        "common.delete": "حذف",
        "common.save": "ذخیره",
        "common.back": "بازگشت",
        "common.confirm": "تأیید",
        "common.upgrade": "ارتقا",
        "common.loading": "بارگذاری…",

        // Tier gating
        "tier.locked_reason.quickLink": "اطلاع + لینک سریع یک قابلیت Pro است",
        "tier.locked_reason.stewardActs": "اقدام Steward یک قابلیت Premium است",
    ]
}
